language: python
sudo: false

env:
  - LUA="lua5.1"
  - LUA="lua5.2"
  - LUA="lua5.3"
  - LUA="luajit2.0"
  - LUA="luajit2.1"

notifications:
  email: false

before_install:
  - pip install hererocks
  - hererocks lua_install -r^ --$LUA
  - export PATH=$PATH:$PWD/lua_install/bin # Add directory with all installed binaries to PATH

install:
  - luarocks install luacheck

script:
  - luacheck --no-unused-args --std *.lua
  - lua test.lua
