dist: trusty
sudo: false
language: lua

before_install:
  - sudo apt-get install luajit
  - sudo apt-get install lua5.2
  - sudo apt-get install lua5.1

before_script:

script:
  - lua5.1 test.lua
  - lua5.2 test.lua
  - luajit test.lua
